// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe43TVNgAAgAdcaK7gOjqUUXAcAQStfhI',
    appId: '1:335770504017:web:73ec033298187101e22170',
    messagingSenderId: '335770504017',
    projectId: 'gkaelyon-4fb9a',
    authDomain: 'gkaelyon-4fb9a.firebaseapp.com',
    storageBucket: 'gkaelyon-4fb9a.firebasestorage.app',
    measurementId: 'G-1KZXKDPR44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5HpUc2G3Cpm7mQumVgzrVTFpH6YIuQiY',
    appId: '1:335770504017:android:5f8c284fb4cff6d7e22170',
    messagingSenderId: '335770504017',
    projectId: 'gkaelyon-4fb9a',
    storageBucket: 'gkaelyon-4fb9a.firebasestorage.app',
  );

}